### ISSUE TITLE
Persistent blur

### ISSUE THREAD

**Issue by Gabe-LS** [vivek-nexus/easy-blur#1]
Hello! It would be great if you could add a way to save blurred items for a specific website so that they will remain blurred forever (unless the user intentionally turns off the blurry option). Thanks.

**Comment by vivek-nexus** [comment]
Hello @Gabriele-LS! Thanks for sharing your feedback!

I can see that there is another extension (paid though) that can keep the blur forever, until removed by the user https://www.blurweb.app/#keep-blur

I understand the need for this. However, because of the following reasons, I did not add this feature
1. By definition, when you reload a web page, there is no guarantee that the contents of the web page will be same as the one before. This is the fundamental nature of web pages. So if I save a reference to a blurred element and when you reload, the website might have updated and the saved reference might not even be valid. Hence, a promise that an element will remain blurred forever is a false one, although it might work until it breaks.
2. To overcome the above issue, some clever solutions can be done. The ones I can think of are very buggy, will break the simplicity of the extension and probably demand a lot of software expertise, which I admit I don't have currently :sweat_smile:


Having said these, if you are comfortable, please list down some situations or examples where you think this feature is very useful. That could help me think about possible solutions as well in the future!

Thanks again!

**Comment by Gabe-LS** [comment]
Hello, @yakshaG! Thanks for replying to my post.

I have already tried Blurweb, but it did not work for me (I couldn't even receive the free trial activation code).

Regarding the situations in which a persistent blur would be needed, I was searching for a solution to blur some sensitive data during a screen recording. Ultimately, I used an extension to inject a custom CSS.

**Comment by vivek-nexus** [comment]
Oh okay. CSS injection solution that you are using is a far more reliable solution than any blurring extension can ever provide. That was really how `Easy Blur` was born as well!

If I ever manage to implement this, I'll surely let you know here!

And since you know CSS injection, probably my explanation in point 1 was a little too much lol.

**Comment by Gabe-LS** [comment]
Thank you @yakshaG!
