### ISSUE TITLE
Incognito windows

### ISSUE THREAD

**Issue by barbmc** [vivek-nexus/easy-blur#7]
Hi there,

I'm loving Easy Blur it does exactly what I want it to. Only trouble is that I can't get it to work when in incognito mode. Is there a way to do this?

Cheers
Barbara

**Comment by vivek-nexus** [comment]
Glad you found **Easy Blur** useful @barbmc !

Chrome extensions are disabled in incognito mode by default, but you can specifically make an extension work in incognito mode. Instructions on this [link](https://support.google.com/chrome/thread/206162749/using-extensions-on-your-incognito).

**Comment by barbmc** [comment]
Thank you so much for that, all good now. Unfortunately I don't think this extension will work for me after all. I need something that will blur personal information I have typed into form fields, before screen recording as well as blurring images of ID cards etc..

So sorry for wasting your time.
________________________________

**Comment by vivek-nexus** [comment]
From what you have described, I don't see a reason why it wouldn't serve your purpose. Once you trigger Easy Blur, if you can get a red border around anything on the web page while hovering, you should be able to blur it (input fields, image tags etc.). In any case, I'll leave the specifics for you to decide.

**Comment by barbmc** [comment]
I was typing info into a login form. Then activating Easy Blur, hovering over the email field and typing b. That blurred the field as it should but it also added a b to my field's contents, making it invalid. What am I doing wrong?

________________________________

**Comment by vivek-nexus** [comment]
Ah I get it! Once you get the red border, you don't need to select the input field again by clicking inside it. Hover and directly press "b", once you get the red border.

**Comment by barbmc** [comment]
So, the trick is keeping the mouse still with your right hand while typing the b with your left. I guess I'm not too good at that lol.

________________________________

**Comment by vivek-nexus** [comment]
Haha. You can take your hand off the mouse/touch pad and the pointer should stay still, until you press "b".

### Why is it like this?
For example, imagine if the element you want to select is a button like "logout". If you had to click to blur it (instead of hover), then the button would log you out and take you to some other page, since you clicked. It is a new page and the button is no longer there! What will you even blur?

PS: You can customise the "b", the "u" and the "q" to any key you want.

**Comment by barbmc** [comment]
You make several very good points. Unfortunately, I am the only person in the world who has been in IT for 50 years and still can't touch type haha. I still really want EB to work for me though, so I will persevere, now I know what the issue is.  Thank you so much for your patience and your wonderful extension!

________________________________

**Comment by barbmc** [comment]
I have now found that Easy Blur does not recognise the hover event when screen recording software (ScreenPal) is active. Is there a workaround for this?

________________________________

**Comment by vivek-nexus** [comment]
It is difficult to provide suggestion on this, since I have never used the specific screen recording software you're talking about. At best I can say is that you might need to focus the web page again for hover to work, if the screen recording software has taken over the focus.

Here is a sample of Easy Bur working while recording screen.
https://www.youtube.com/watch?v=5e6j2PP39mg

**Comment by barbmc** [comment]
Screenpal used to be Sceencast-O-Matic. I don't see any screen recorder in that video. How do I  get the focus back without breaking EB?

________________________________

**Comment by vivek-nexus** [comment]
Really difficult to provide any support here. Switch windows, minimise and maximise Chrome, click somewhere inside the webpage etc. You have to keep trying what works and figure it out yourself.
